#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server's hostname

apt-get update -y
apt-get install -y nginx

# shellcheck disable=SC2154
sudo sed -i "/http {/a \\\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

sudo service nginx restart
