#!/usr/bin/env bash

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx stop
service nginx start
