#!/usr/bin/env bash
# Installs and configures nginx to serve a page containing "Holberton School"

apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx restart
