#!/usr/bin/env bash
# Configuring Nginx with a custom 404 page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
